definitions:
  models.HelloStcruct:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: MelodyStatusのAPI一覧だよ
  license:
    name: tetn39
  title: MelodyStatusのAPI一覧
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Hello Worldを返すだけのテスト用
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HelloStcruct'
      summary: hello worldを返す
      tags:
      - Hello World
swagger: "2.0"
